# Generated by Django 6.0.7 on 2026-09-18 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Temperature',
            new_name='Temperature_db',
        ),
    ]
